# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 862b345b2d5c72b483301d4744936c28c94d4982129568a68a88c12b086c67b2edf58e076d5b68081da6442878e710945233a5cdce3be06bbd1ff4e86ce1adff

test:
  secret_key_base: 58356dbd3eaba23a363b96b42dd4bdba2b5095e5ab838538086e76fc630b339313339bca0b88f467487bbc8dfb3a3df001a27538579876c966ce77eab8b6e6f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
